apiVersion: v2
name: giga-actions
description: The list of actions release
type: application
version: 0.1.4
appVersion: 0.1.0
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
maintainers:
  - email: dev@catex.se
    name: Catexer
