apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: local
spec:
  interval: 10m
  timeout: 5m
  releaseName: sealed-secrets-controller
  chart:
    spec:
      chart: sealed-secrets
      version: ">=1.15.0-0"
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: flux-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
