apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: eks
  labels:
    provider: aws
    service: eks
    compute: managed
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: gigapress.catex.se/v1beta1
    kind: Org

  patchSets:
    - name: common
      patches:
        - fromFieldPath: "spec.region"
          toFieldPath: "spec.forProvider.region"

  resources:
    - name: vpc
      base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: VPC
        spec:
          forProvider:
            enableDnsSupport: true
            enableDnsHostNames: true
            tags:
              - key: Name
      patches:
        - type: PatchSet
          patchSetName: common
        - fromFieldPath: spec.vpc.cidrBlock
          toFieldPath: spec.forProvider.cidrBlock
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: spec.prefix
              - fromFieldPath: spec.name
            strategy: string
            string:
              fmt: "%s-%s"
          toFieldPath: spec.forProvider.tags[0].value
          policy:
            fromFieldPath: Required

    - name: igw
      base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: InternetGateway
        metadata:
          labels:
            type: igw
        spec:
          forProvider:
            vpcIdSelector:
              matchControllerRef: true
            tags:
              - key: Name
      patches:
        - type: PatchSet
          patchSetName: common
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: spec.prefix
              - fromFieldPath: spec.name
            strategy: string
            string:
              fmt: "igw-%s-%s"
          toFieldPath: spec.forProvider.tags[0].value
          policy:
            fromFieldPath: Required

    - name: subnet-public-1
      base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: Subnet
        metadata:
          labels:
            type: subnet
            visibility: public
        spec:
          forProvider:
            mapPublicIpOnLaunch: true
            vpcIdSelector:
              matchControllerRef: true
            tags:
              - key: Name
              - key: kubernetes.io/role/elb
                value: "1"
      patches:
        - type: PatchSet
          patchSetName: common
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: spec.prefix
              - fromFieldPath: spec.name
              - fromFieldPath: spec.vpc.subnet-public-1.name
            strategy: string
            string:
              fmt: "%s-%s-%s"
          toFieldPath: spec.forProvider.tags[0].value
          policy:
            fromFieldPath: Required
        - fromFieldPath: spec.vpc.subnet-public-1.cidrBlock
          toFieldPath: spec.forProvider.cidrBlock
        - fromFieldPath: spec.vpc.subnet-public-1.az
          toFieldPath: spec.forProvider.availabilityZone
        - fromFieldPath: spec.vpc.subnet-public-1.az
          toFieldPath: metadata.labels.zone

    - name: subnet-public-2
      base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: Subnet
        metadata:
          labels:
            type: subnet
            visibility: public
        spec:
          forProvider:
            mapPublicIpOnLaunch: true
            vpcIdSelector:
              matchControllerRef: true
            tags:
              - key: Name
              - key: kubernetes.io/role/elb
                value: "1"
      patches:
        - type: PatchSet
          patchSetName: common
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: spec.prefix
              - fromFieldPath: spec.name
              - fromFieldPath: spec.vpc.subnet-public-2.name
            strategy: string
            string:
              fmt: "%s-%s-%s"
          toFieldPath: spec.forProvider.tags[0].value
          policy:
            fromFieldPath: Required
        - fromFieldPath: spec.vpc.subnet-public-2.cidrBlock
          toFieldPath: spec.forProvider.cidrBlock
        - fromFieldPath: spec.vpc.subnet-public-2.az
          toFieldPath: spec.forProvider.availabilityZone
        - fromFieldPath: spec.vpc.subnet-public-2.az
          toFieldPath: metadata.labels.zone

    - name: subnet-private-1
      base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: Subnet
        metadata:
          labels:
            type: subnet
            visibility: private
        spec:
          forProvider:
            mapPublicIpOnLaunch: false
            vpcIdSelector:
              matchControllerRef: true
            tags:
              - key: Name
              - key: kubernetes.io/role/internal-elb
                value: "1"
      patches:
        - type: PatchSet
          patchSetName: common
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: spec.prefix
              - fromFieldPath: spec.name
              - fromFieldPath: spec.vpc.subnet-private-1.name
            strategy: string
            string:
              fmt: "%s-%s-%s"
          toFieldPath: spec.forProvider.tags[0].value
          policy:
            fromFieldPath: Required
        - fromFieldPath: spec.vpc.subnet-private-1.cidrBlock
          toFieldPath: spec.forProvider.cidrBlock
        - fromFieldPath: spec.vpc.subnet-private-1.az
          toFieldPath: spec.forProvider.availabilityZone
        - fromFieldPath: spec.vpc.subnet-private-1.az
          toFieldPath: metadata.labels.zone

    - name: subnet-private-2
      base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: Subnet
        metadata:
          labels:
            type: subnet
            visibility: private
        spec:
          forProvider:
            mapPublicIpOnLaunch: false
            vpcIdSelector:
              matchControllerRef: true
            tags:
              - key: Name
              - key: kubernetes.io/role/internal-elb
                value: "1"
      patches:
        - type: PatchSet
          patchSetName: common
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: spec.prefix
              - fromFieldPath: spec.name
              - fromFieldPath: spec.vpc.subnet-private-2.name
            strategy: string
            string:
              fmt: "%s-%s-%s"
          toFieldPath: spec.forProvider.tags[0].value
          policy:
            fromFieldPath: Required
        - fromFieldPath: spec.vpc.subnet-private-2.cidrBlock
          toFieldPath: spec.forProvider.cidrBlock
        - fromFieldPath: spec.vpc.subnet-private-2.az
          toFieldPath: spec.forProvider.availabilityZone
        - fromFieldPath: spec.vpc.subnet-private-2.az
          toFieldPath: metadata.labels.zone

    - name: elastic-ip
      base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: Address
        metadata:
          labels:
            type: eip
        spec:
          forProvider:
            domain: vpc
      patches:
        - type: PatchSet
          patchSetName: common

    - name: natgateway
      base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: NATGateway
        metadata:
          labels:
            type: natgw
        spec:
          forProvider:
            allocationIdSelector:
              matchLabels:
                type: eip
            vpcIdSelector:
              matchControllerRef: true
            subnetIdSelector:
              matchLabels:
                type: subnet
                visibility: public
            tags:
              - key: Name
      patches:
        - type: PatchSet
          patchSetName: common
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: spec.prefix
              - fromFieldPath: spec.name
            strategy: string
            string:
              fmt: "natgw-%s-%s"
          toFieldPath: spec.forProvider.tags[0].value
          policy:
            fromFieldPath: Required
        # - fromFieldPath: spec.vpc.subnet-public-1.az
        #   toFieldPath: spec.forProvider.subnetIdSelector.matchLabels.zone

    - name: routetable-public
      base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: RouteTable
        spec:
          forProvider:
            vpcIdSelector:
              matchControllerRef: true
            routes:
              - destinationCidrBlock: 0.0.0.0/0
                gatewayIdSelector:
                  matchLabels:
                    type: igw
            associations:
              - subnetIdSelector:
                  matchLabels:
                    type: subnet
                    visibility: public
              - subnetIdSelector:
                  matchLabels:
                    type: subnet
                    visibility: public
            tags:
              - key: Name
      patches:
        - type: PatchSet
          patchSetName: common
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: spec.prefix
              - fromFieldPath: spec.name
            strategy: string
            string:
              fmt: "public-routeable-%s-%s"
          toFieldPath: spec.forProvider.tags[0].value
          policy:
            fromFieldPath: Required
        - fromFieldPath: spec.vpc.subnet-public-1.az
          toFieldPath: spec.forProvider.associations[0].subnetIdSelector.matchLabels.zone
        - fromFieldPath: spec.vpc.subnet-public-2.az
          toFieldPath: spec.forProvider.associations[1].subnetIdSelector.matchLabels.zone

    - name: routetable-private-1
      base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: RouteTable
        spec:
          forProvider:
            vpcIdSelector:
              matchControllerRef: true
            routes:
              - destinationCidrBlock: 0.0.0.0/0
                natGatewayIdSelector:
                  matchLabels:
                    type: natgw
            associations:
              - subnetIdSelector:
                  matchLabels:
                    type: subnet
                    visibility: private
            tags:
              - key: Name
      patches:
        - type: PatchSet
          patchSetName: common
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: spec.prefix
              - fromFieldPath: spec.name
            strategy: string
            string:
              fmt: "private-routetable-1-%s-%s"
          toFieldPath: spec.forProvider.tags[0].value
          policy:
            fromFieldPath: Required
        - fromFieldPath: spec.vpc.subnet-private-1.az
          toFieldPath: spec.forProvider.associations[0].subnetIdSelector.matchLabels.zone

    - name: routetable-private-2
      base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: RouteTable
        spec:
          forProvider:
            vpcIdSelector:
              matchControllerRef: true
            routes:
              - destinationCidrBlock: 0.0.0.0/0
                natGatewayIdSelector:
                  matchLabels:
                    type: natgw
            associations:
              - subnetIdSelector:
                  matchLabels:
                    type: subnet
                    visibility: private
            tags:
              - key: Name
      patches:
        - type: PatchSet
          patchSetName: common
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: spec.prefix
              - fromFieldPath: spec.name
            strategy: string
            string:
              fmt: "private-routetable-2-%s-%s"
          toFieldPath: spec.forProvider.tags[0].value
          policy:
            fromFieldPath: Required
        - fromFieldPath: spec.vpc.subnet-private-2.az
          toFieldPath: spec.forProvider.associations[0].subnetIdSelector.matchLabels.zone

    - name: eks-cluster
      base:
        apiVersion: eks.aws.crossplane.io/v1beta1
        kind: Cluster
        spec:
          forProvider:
            resourcesVpcConfig:
              endpointPrivateAccess: false
              endpointPublicAccess: true
              subnetIdSelector:
                matchLabels:
                  type: subnet
      patches:
        - type: PatchSet
          patchSetName: common
        - fromFieldPath: "spec.eks.k8s-version"
          toFieldPath: "spec.forProvider.version"
        - fromFieldPath: "metadata.uid"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
            - type: string
              string:
                fmt: "eks-%s"
        - fromFieldPath: "spec.eks.cluster-role"
          toFieldPath: "spec.forProvider.roleArn"
      connectionDetails:
        - name: cluster-ca
          fromConnectionSecretKey: clusterCA
        - name: cluster-endpoint
          fromConnectionSecretKey: endpoint
        - name: cluster-value
          fromConnectionSecretKey: kubeconfig

    - name: eks-nodegroup
      base:
        apiVersion: eks.aws.crossplane.io/v1alpha1
        kind: NodeGroup
        spec:
          forProvider:
            instanceTypes:
              - m5.large
            scalingConfig:
              minSize: 3
            subnetSelector:
              matchLabels:
                type: subnet
                visibility: private
            clusterNameSelector:
              matchControllerRef: true
      patches:
        - type: PatchSet
          patchSetName: common
        - fromFieldPath: "spec.eks.workers-size"
          toFieldPath: "spec.forProvider.scalingConfig.desiredSize"
        - fromFieldPath: "spec.eks.workers-size"
          toFieldPath: "spec.forProvider.scalingConfig.maxSize"
        - fromFieldPath: "spec.eks.workload-type"
          toFieldPath: "spec.forProvider.amiType"
          transforms:
          - type: map
            map:
              gpu: AL2_x86_64_GPU
              non-gpu: AL2_x86_64
        - fromFieldPath: "spec.eks.workernode-role"
          toFieldPath: "spec.forProvider.nodeRole"
