apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xorgs.gigapress.catex.se
spec:
  group: gigapress.catex.se
  names:
    kind: XOrg
    plural: xorgs
  claimNames:
    kind: Org
    plural: orgs
  defaultCompositionRef:
    name: org-standard.aws.gigapress.catex.se
  connectionSecretKeys:
    - cluster-ca
    - cluster-endpoint
    - cluster-value
  versions:
  - name: v1beta1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                description: The unique name applied for all resources
                type: string

              prefix:
                description: The prefix applied naming for all resources
                type: string

              region:
                description: Geographic location of this VPC
                type: string
                enum:
                - eu-north-1
                - eu-west-1

              eks:
                type: object
                properties:
                  cluster-role:
                    description: EKS cluster role
                    type: string
                  k8s-version:
                    description: Kubernetes version
                    type: string
                    enum: ["1.20", "1.21", "1.22"]
                  workers-size:
                    description: Desired number of worker nodes
                    type: integer
                  workernode-role:
                    description: EKS worker node role
                    type: string
                  workload-type:
                    description: Type of workloads (GPU or non-GPU)"
                    type: string
                    enum: ["gpu", "non-gpu"]

                required:
                  - cluster-role
                  - k8s-version
                  - workernode-role
                  - workers-size
                  - workload-type

              vpc:
                type: object
                properties:
                  cidrBlock:
                    description: CIDR block for VPC
                    type: string

                  subnet-public-1:
                    type: object
                    properties:
                      name:
                        description: Name for subnet
                        type: string
                      cidrBlock:
                        description: CIDR block for subnet
                        type: string
                      az:
                        decription: AZ for subnet
                        type: string
                    required:
                      - name
                      - cidrBlock
                      - az

                  subnet-public-2:
                    type: object
                    properties:
                      name:
                        description: Name for subnet
                        type: string
                      cidrBlock:
                        description: CIDR block for subnet
                        type: string
                      az:
                        decription: AZ for subnet
                        type: string
                    required:
                      - name
                      - cidrBlock
                      - az

                  subnet-private-1:
                    type: object
                    properties:
                      name:
                        description: Name for subnet
                        type: string
                      cidrBlock:
                        description: CIDR block for subnet
                        type: string
                      az:
                        decription: AZ for subnet
                        type: string
                    required:
                      - name
                      - cidrBlock
                      - az

                  subnet-private-2:
                    type: object
                    properties:
                      name:
                        description: Name for subnet
                        type: string
                      cidrBlock:
                        description: CIDR block for subnet
                        type: string
                      az:
                        decription: AZ for subnet
                        type: string
                    required:
                      - name
                      - cidrBlock
                      - az

                required:
                  - cidrBlock
                  - subnet-public-1
                  - subnet-public-2
                  - subnet-private-1
                  - subnet-private-2

            required:
              - eks
              - vpc
              - name
              - prefix
              - region
