apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: local
spec:
  interval: 10m
  releaseName: redis
  chart:
    spec:
      chart: redis
      version: 12.10.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    usePassword: false
    cluster:
      enabled: false
    master:
      disableCommands: ["FLUSHALL"]
      persistence:
        enabled: true
