apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: flux-system
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QUtJQVdNMlBIUTNDRUhJMjdQNU8=
  AWS_SECRET_ACCESS_KEY: enN6TENaeEdJMTIzTnJXQmYwT2lNWVBkMWZaMDZaeGRRckt4NDhaSA==
