#!/usr/bin/env bash

set -e

CONTEXT=${1:-gigapress}
CLUSTER=${2:-local}

flux bootstrap gitlab \
  --owner=pangara/gigapress \
  --repository=gitops \
  --branch=master \
  --context=$CONTEXT \
  --path="clusters/${CLUSTER}" \
  --components-extra=image-reflector-controller,image-automation-controller
