apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gigapress
  labels:
    app: gigapress
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: terminal
            port:
              number: 8055
