apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: terminal
spec:
  releaseName: terminal
  interval: 1m
  timeout: 5m
  chart:
    spec:
      chart: terminal-0.1.0.tgz
      sourceRef:
        kind: Bucket
        name: pangara-charts
        namespace: flux-system
  values:
    replicaCount: 1
    pullPolicy: Always
    image: 439863445188.dkr.ecr.ap-southeast-1.amazonaws.com/gigapress/core:dev # {"$imagepolicy": "flux-system:terminal"}
    serviceAccount:
      create: true

    service:
      type: LoadBalancer

    readiness:
      enable: false
      initialDelaySeconds: 30
      periodSeconds: 120

    liveness:
      enable: false
      initialDelaySeconds: 30
      periodSeconds: 120

    env:
      KEY: 255d861b-5ea1-5996-9aa3-922530ec40b1
      SECRET: 6116487b-cda1-52c2-b5b5-c8022c45e263

      DB_CLIENT: mysql
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_DATABASE: directus
      DB_USER: directus
      DB_PASSWORD: directus

      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWORD: admin123

      CACHE_ENABLED: true
      CACHE_STORE: redis
      CACHE_REDIS: redis://redis-headless:6379

