apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: org-composition
spec:
  package: public.ecr.aws/catext/gigapress/crossplane-org:0.1.10
  packagePullPolicy: Always
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 0
  skipDependencyResolution: false
