apiVersion: v1
kind: Namespace
metadata:
  name: realm-catex
---
apiVersion: gigapress.catex.se/v1alpha1
kind: Org
metadata:
  name: catex
  namespace: realm-catex
spec:
  name: catex
  region: eu-north-1
  deletionPolicy: Delete

  eks:
    k8s-version: "1.21"
    cluster-role: arn:aws:iam::221168245729:role/eks-cluster-role
    workernode-role: arn:aws:iam::221168245729:role/node-group-role
    workernode-type: "t3.medium"
    workers-size: 3

  vpc:
    cidrClassB: "10.1"

    subnet-public-1:
      name: "public-1"
      az: "eu-north-1a"

    subnet-public-2:
      name: "public-2"
      az: "eu-north-1b"

    subnet-public-3:
      name: "public-3"
      az: "eu-north-1c"

    subnet-private-1:
      name: "private-1"
      az: "eu-north-1a"

    subnet-private-2:
      name: "private-2"
      az: "eu-north-1b"

    subnet-private-3:
      name: "private-3"
      az: "eu-north-1c"

  compositionRef:
    name: org-standard.aws.gigapress.catex.se

  writeConnectionSecretToRef:
    name: org
---
apiVersion: gigapress.catex.se/v1alpha1
kind: MySQLInstance
metadata:
  name: catex-primary
  namespace: realm-catex
spec:
  orgRefName: catex
  name: primary
  region: eu-north-1
  deletionPolicy: Delete
  instanceClass: "db.t3.micro"
  storageGB: 20
  compositionRef:
    name: mysqlinstance.aws.gigapress.catex.se
  writeConnectionSecretToRef:
    name: mysql
