---
# test-install.catex.se
apiVersion: gigapress.catex.se/v1alpha1
kind: Workspace
metadata:
  name: itest34
  namespace: realm-catex
spec:
  name: itest34
  dbRefName: primary
  orgRefName: catex

  region: eu-north-1
  subdomain: itest34
  domain: catex.se

  app:
    adminEmail: admin@catex.se
    adminPassword: admin123
    image: 221168245729.dkr.ecr.eu-north-1.amazonaws.com/gigapress/core
    version: 2.1.0
    chartVersion: 0.4.16

  installFromTpl:
    enabled: true
    name: hipgnosis
    version: "2022-12-29"
    s3Bucket: catex-templates

  extensions:
    - name: "@giga-extensions/base"
      version: 1.0.2
    - name: "@giga-extensions/pro"
      version: 1.0.0

  writeConnectionSecretToRef:
    name: itest34
