---
# itest61.catex.se
apiVersion: gigapress.catex.se/v1alpha1
kind: Workspace
metadata:
  name: itest61
  namespace: realm-catex
spec:
  name: itest61
  dbRefName: sec
  orgRefName: catex

  region: eu-north-1
  subdomain: itest61
  domain: catex.se

  app:
    adminEmail: admin@catex.se
    adminPassword: admin123
    image: 221168245729.dkr.ecr.eu-north-1.amazonaws.com/gigapress/core
    version: 2.1.4
    chartVersion: 0.5.14
    env:
      MEILISEARCH_API_KEY: W74jflgAqOaAZOfIFbuJ

  extensions:
    - name: "@giga-extensions/base"
      version: 1.0.4
    - name: "@giga-extensions/pro"
      version: 1.0.0

  meilisearch:
    enabled: true
    extVersion: 1.0.1-dev

  writeConnectionSecretToRef:
    name: itest61
