apiVersion: gigapress.catex.se/v1alpha1
kind: Workspace
metadata:
  name: catex-default
  namespace: realm-catex
spec:
  name: default
  dbRefName: primary
  orgRefName: catex

  region: eu-north-1
  subdomain: default
  domain: catex.se

  app:
    adminEmail: admin@catex.se
    adminPassword: admin123
    image: 221168245729.dkr.ecr.eu-north-1.amazonaws.com/gigapress/core
    version: 2.0.0
    chartVersion: 0.1.6
    size: 1

  compositionRef:
    name: workspace.aws.gigapress.catex.se

  writeConnectionSecretToRef:
    name: catex-default
