apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
metadata:
  name: giga-manager
  labels:
    ref.crossplane.io/vpc-manager-cluster: "true"
  annotations:
    crossplane.io/external-name: vpc-098a9be78302ed283
spec:
  deletionPolicy: Orphan
  forProvider:
    region: eu-north-1
    cidrBlock: 10.0.0.0/16
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: RouteTable
metadata:
  name: manager-private-routetable
  labels:
    ref.crossplane.io/manager-private-routetable: "true"
  annotations:
    crossplane.io/external-name: rtb-0071b7d408877e423
spec:
  deletionPolicy: Orphan
  forProvider:
    ignoreRoutes: true
    region: eu-north-1
    associations:
      - subnetId: subnet-07a470ad0ca4c7ead
      - subnetId: subnet-04ab2032ed79a61a7
      - subnetId: subnet-001fe1ed71f655998
---
apiVersion: route53.aws.crossplane.io/v1alpha1
kind: HostedZone
metadata:
  name: catex.se
  labels:
    ref.crossplane.io/hostzone: "catex.se"
  annotations:
    crossplane.io/external-name: Z04205131JTMRBN6ZICQR
spec:
  deletionPolicy: Orphan
  forProvider:
    name: catex.se
