apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: realm-catex
  labels:
    app: mariadb
spec:
  type: ExternalName
  externalName: gigapress-catex-primary.cseks2czrr78.eu-north-1.rds.amazonaws.com
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: db-sec
  namespace: realm-catex
  labels:
    app: db-sec
spec:
  type: ExternalName
  externalName: gigapress-catex-sec.cseks2czrr78.eu-north-1.rds.amazonaws.com
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
