apiVersion: v1
kind: Namespace
metadata:
  name: realm-catex
---
apiVersion: gigapress.catex.se/v1alpha1
kind: XOrg
metadata:
  name: catex
  # annotations:
  #   crossplane.io/external-name: org-catex
spec:
  name: catex
  region: eu-north-1
  deletionPolicy: Delete

  eks:
    k8s-version: "1.21"
    cluster-role: arn:aws:iam::221168245729:role/eks-cluster-role
    workernode-role: arn:aws:iam::221168245729:role/node-group-role
    workernode-type: "t3.medium"
    workers-size: 3
    workload-type: "non-gpu"

  vpc:
    cidrBlock: "10.0.0.0/16"

    subnet-public-1:
      name: "public-1"
      cidrBlock: "10.0.1.0/24"
      az: "eu-north-1a"

    subnet-public-2:
      name: "public-2"
      cidrBlock: "10.0.2.0/24"
      az: "eu-north-1b"

    subnet-private-1:
      name: "private-1"
      cidrBlock: "10.0.101.0/24"
      az: "eu-north-1a"

    subnet-private-2:
      name: "private-2"
      cidrBlock: "10.0.102.0/24"
      az: "eu-north-1b"

  compositionRef:
    name: org-standard.aws.gigapress.catex.se

  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: org-catex
---
apiVersion: gigapress.catex.se/v1alpha1
kind: Org
metadata:
  name: catex
  namespace: realm-catex
  # annotations:
  #   crossplane.io/external-name: org-catex
spec:
  name: catex
  region: eu-north-1
  deletionPolicy: Delete

  resourceRef:
    apiVersion: gigapress.catex.se/v1alpha1
    kind: XOrg
    name: catex

  writeConnectionSecretToRef:
    name: org-details
