apiVersion: v1
kind: Pod
metadata:
  name: debug
spec:
  containers:
  - image: ubuntu
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: debug
    securityContext:
      allowPrivilegeEscalation: false
      runAsUser: 0
  restartPolicy: Always

