apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: mysqlinstance.aws.gigapress.catex.se
  labels:
    crossplane.io/xrd: xmysqlinstances.gigapress.catex.se
    provider: aws
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: gigapress.catex.se/v1alpha1
    kind: XMySQLInstance

  patchSets:
    - name: common
      patches:
        - fromFieldPath: "spec.region"
          toFieldPath: "spec.forProvider.region"
        - fromFieldPath: "spec.deletionPolicy"
          toFieldPath: "spec.deletionPolicy"

  # -----------------
  # RM includes
  # -----------------
  # - DBSubnetGroup
  # - RDSInstance
  # - DBParameterGroup
  # - VPCEndpoint
  # -----------------

  resources:
    # DB :: Subnet Group
    - name: dbsubnetgroup
      base:
        apiVersion: database.aws.crossplane.io/v1beta1
        kind: DBSubnetGroup
        spec:
          forProvider:
            description: "The subnet group of rds"
            subnetIdSelector:
              matchLabels:
                type: subnet
                visibility: private
      patches:
        - type: PatchSet
          patchSetName: common
        - fromFieldPath: spec.orgRefName
          toFieldPath: spec.forProvider.subnetIdSelector.matchLabels[ref.crossplane.io/org-name]

    # DB :: Mysql Instance
    - name: rds
      base:
        apiVersion: database.aws.crossplane.io/v1beta1
        kind: RDSInstance
        spec:
          forProvider:
            dbSubnetGroupNameSelector:
              matchControllerRef: true
            dbInstanceClass: db.t3.small
            engine: mariadb
            engineVersion: "10.4"
            masterUsername: master
            skipFinalSnapshotBeforeDeletion: true
            publicAccessible: false
            vpcSecurityGroupIDSelector:
              matchLabels:
                type: rds-connection
          writeConnectionSecretToRef:
            namespace: crossplane-system
      patches:
        - type: PatchSet
          patchSetName: common
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: spec.orgRefName
              - fromFieldPath: spec.name
            strategy: string
            string:
              fmt: "database-%s-%s"
          toFieldPath: spec.writeConnectionSecretToRef.name
          policy:
            fromFieldPath: Required
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: spec.orgRefName
              - fromFieldPath: spec.name
            strategy: string
            string:
              fmt: "gigapress-%s-%s"
          toFieldPath: metadata.name
          policy:
            fromFieldPath: Required
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: spec.orgRefName
              - fromFieldPath: spec.name
            strategy: string
            string:
              fmt: "dpg-%s-%s"
          toFieldPath: spec.forProvider.dbParameterGroupName
        - fromFieldPath: spec.storageGB
          toFieldPath: spec.forProvider.allocatedStorage
        - fromFieldPath: spec.instanceClass
          toFieldPath: spec.forProvider.dbInstanceClass
        - fromFieldPath: spec.orgRefName
          toFieldPath: spec.forProvider.vpcSecurityGroupIDSelector.matchLabels[ref.crossplane.io/org-name]

    # RDS :: parameter-group
    - name: db-parameter-group
      base:
        apiVersion: rds.aws.crossplane.io/v1alpha1
        kind: DBParameterGroup
        spec:
          forProvider:
            dbParameterGroupFamilySelector:
              engine: mariadb
              engineVersion: "10.4"
            description: the custom parameter for db instances
            parameters:
              - parameterName: table_definition_cache
                parameterValue: "1024"
                applyMethod: immediate
      patches:
        - type: PatchSet
          patchSetName: common
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: spec.orgRefName
              - fromFieldPath: spec.name
            strategy: string
            string:
              fmt: "dpg-%s-%s"
          toFieldPath: metadata.name
          policy:
            fromFieldPath: Required
