apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: rds.aws.gigapress.catex.se
  labels:
    crossplane.io/xrd: xworkspaces.gigapress.catex.se
    provider: aws
    type: workspace
    tier: enterprise
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: gigapress.catex.se/v1alpha1
    kind: XWorkspace

  patchSets:
    - name: common
      patches:
        - fromFieldPath: "spec.region"
          toFieldPath: "spec.forProvider.region"
        - fromFieldPath: "spec.deletionPolicy"
          toFieldPath: "spec.deletionPolicy"

  resources:

    - name: dbsubnetgroup
      base:
        apiVersion: database.aws.crossplane.io/v1beta1
        kind: DBSubnetGroup
        spec:
          forProvider:
            subnetIdSelector:
              matchLabels:
                type: subnet
                visibility: private
      patches:
        - type: PatchSet
          patchSetName: common
        - fromFieldPath: "spec.vpcName"
          toFieldPath: "spec.forProvider.subnetIdSelector.matchLabels[vpc]"

    - name: rds
      base:
        apiVersion: database.aws.crossplane.io/v1beta1
        kind: RDSInstance
        spec:
          forProvider:
            dbSubnetGroupNameSelector:
              matchControllerRef: true
            allocatedStorage: 20
            dbInstanceClass: db.t3.small
            engine: mariadb
            engineVersion: "10.4"
            masterUsername: master
            skipFinalSnapshotBeforeDeletion: true
      patches:
        - type: PatchSet
          patchSetName: common
        - fromFieldPath: "metadata.uid"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
            - type: string
              string:
                fmt: "mysql-%s"
        - fromFieldPath: "spec.name"
          toFieldPath: "metadata.name"
          transforms:
            - type: string
              string:
                fmt: "org-%s"
        - fromFieldPath: "spec.name"
          toFieldPath: "spec.forProvider.dbParameterGroupName"
          transforms:
            - type: string
              string:
                fmt: "org-%s"
        - fromFieldPath: "spec.storageGB"
          toFieldPath: "spec.forProvider.allocatedStorage"
        - fromFieldPath: "spec.dbVersion"
          toFieldPath: "spec.forProvider.engineVersion"
        - fromFieldPath: "spec.instanceClass"
          toFieldPath: "spec.forProvider.dbInstanceClass"
      connectionDetails:
        - fromConnectionSecretKey: username
        - fromConnectionSecretKey: password
        - fromConnectionSecretKey: endpoint
        - fromConnectionSecretKey: port

    - name: securitygroup
      base:



