apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: mysqlinstances.gigapress.catex.se
spec:
  group: gigapress.catex.se
  names:
    kind: XMySQLInstance
    plural: xmysqlinstances
  claimNames:
    kind: MySQLInstance
    plural: mysqlinstances
  # connectionSecretKeys:
  #   - username
  #   - password
  #   - endpoint
  #   - port
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string
                description: The db instance name
              region:
                type: string
                description: The region which resource setup to
              instanceClass:
                type: string
                description: The instance type
              storageGB:
                type: string
                description: The allocated storage of db instance
              orgRefName:
                type: string
                description: A ref to org resource by name
            required:
              - name
              - storageGB
              - region
              - orgRefName

