{{- if .Values.webapp.sa.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.webapp.sa.name }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  {{- with .Values.webapp.sa.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with .Values.webapp.sa.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.webapp.sa.name }}-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.webapp.sa.name }}-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.webapp.sa.name }}-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.webapp.sa.name }}
{{- end -}}
