apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webapp.svc.name }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    gigapress.catex.se/app_name: webapp
  {{- with .Values.webapp.svc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.webapp.svc.type }}
  ports:
    - port: {{ .Values.webapp.svc.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
    gigapress.catex.se/app_name: webapp
