apiVersion: batch/v1
kind: Job
metadata:
  name: sync-ecr-pullsecret
spec:
  template:
    spec:
      serviceAccountName: ecr-credentials-sync
      restartPolicy: Never
      volumes:
      - name: token
        emptyDir:
          medium: Memory
      initContainers:
      - image: amazon/aws-cli
        name: get-token
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: aws-credentials
        env:
        - name: REGION
          value: ap-southeast-1
        volumeMounts:
        - mountPath: /token
          name: token
        command:
        - /bin/sh
        - -ce
        - aws ecr get-login-password --region ${REGION} > /token/ecr-token
      containers:
      - image: bitnami/kubectl
        name: create-secret
        imagePullPolicy: IfNotPresent
        env:
        - name: SECRET_NAME
          value: image-pull-secret-src
        - name: ECR_REGISTRY
          value: 439863445188.dkr.ecr.ap-southeast-1.amazonaws.com
        volumeMounts:
        - mountPath: /token
          name: token
        command:
        - /bin/bash
        - -ce
        - |-
          kubectl create secret docker-registry $SECRET_NAME \
            --dry-run=client \
            --docker-server="$ECR_REGISTRY" \
            --docker-username=AWS \
            --docker-password="$(</token/ecr-token)" \
            -o yaml | kubectl apply -f -
  backoffLimit: 1
