apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}
data:
  site: |
    map $sent_http_content_type $expires {
        "text/html"                 epoch;
        "text/html; charset=utf-8"  epoch;
        default                     off;
    }

    server {
        listen          80;
        server_name     localhost;

        gzip            on;
        gzip_types      text/plain application/xml text/css application/javascript;
        gzip_min_length 1000;

        location = /robots.txt {
          add_header Content-Type text/plain;
          return 200 "User-agent: *\nDisallow: /\n";
        }

        location / {
            expires $expires;

            proxy_redirect                      off;
            proxy_set_header Host               $host;
            proxy_set_header X-Real-IP          $remote_addr;
            proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto  $scheme;
            proxy_read_timeout                  1m;
            proxy_connect_timeout               1m;
            proxy_pass                          http://127.0.0.1:3000;
        }

    }

  nginx.conf: |
    worker_processes 1;
    pid /run/nginx.pid;

    events {
      worker_connections  2048;
      multi_accept on;
      use epoll;
    }

    http {
      log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
      fastcgi_read_timeout 120;
      proxy_read_timeout 120;

      include /etc/nginx/mime.types;
      default_type  application/octet-stream;
      client_max_body_size 20M;
      sendfile        on;
      keepalive_timeout  80;

      access_log /dev/stdout main;
      error_log /dev/stderr;
      gzip on;
      gzip_disable "msie6";

      include /etc/nginx/sites-available/*.conf;
      include /etc/nginx/conf.d/*.conf;
      open_file_cache off;
      charset UTF-8;
    }
