apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: base
  namespace: crossplane-system
spec:
  interval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./clusters/manager/crossplane-system/base
  validation: client
  prune: false
  timeout: 120s
