apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: main
  namespace: crossplane-system
spec:
  interval: 2m
  dependsOn:
    - name: base
    - name: provider
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./clusters/manager/crossplane-system/main
  prune: true
  timeout: 120s
