replicaCount: 1

image:
pullPolicy: IfNotPresent

serviceAccount:
  create: true
  imagePullSecrets:
    - name: ecr-registry-key
  # annotations: {}
  name: terminal

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: NodePort
  port: 8055
  annotations: {}

env:
  SENTRY_ENV: sample
  SENTRY_DSN: sample
  SENTRY_DISABLED: "true"

extendEnv:

resources:
  limits:
    cpu: 1
    memory: 1280Mi
  requests:
    cpu: 100m
    memory: 128Mi

readiness:
  enable: false
  path:
  periodSeconds:
  timeoutSeconds:
  initialDelaySeconds:

liveness:
  enable: false
  path:
  periodSeconds:
  timeoutSeconds:
  initialDelaySeconds:

ingress:
  enabled: false
  certManager: false
  pathType: ImplementationSpecific
  apiVersion:
  hostname: sample.local
  path: /
  annotations: {}
  tls: false
  extraHosts:
  extraTls: []
  secrets:

extensions: []
# - name
#   version

npm:
  repo: gigapress
  domain: catex
  owner: "221168245729"
  scope: "@giga-extensions"

redis:
  architecture: standalone
  auth:
    enabled: false
  cluster:
    enabled: false
  master:
    disableCommands: ["FLUSHALL"]
    persistence:
      size: 500Mi
      enabled: true

actions:
  cronPublishTpl:
    name: ""
    schedule: "0 0 * * *"
    enabled: false
    s3Bucket: "catex-template"
    runAt: ""
