{{- if .Values.actions.cronPublishTpl.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "chart.fullname" . }}-publish-tpl
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.actions.cronPublishTpl.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ include "chart.serviceAccountName" . }}
          restartPolicy: OnFailure
          containers:
          - name: node
            image: node:16
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - "-c"
            - |
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              unzip awscliv2.zip && ./aws/install
              npx directus schema snapshot --yes ./snapshot.yaml
              aws s3 cp ./snapshot.yaml s3://{{ .Values.actions.cronPublishTpl.s3Bucket }}/{{.Values.actions.cronPublishTpl.name}}/{{ now }}.yaml

            {{- if .Values.appSecretName }}
            envFrom:
            - secretRef:
                name: {{ .Values.appSecretName }}
            {{- end }}

            env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}

            {{- if .Values.extendEnv }}
            {{- range $key, $value := .Values.extendEnv }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}

{{- end }}
---
{{- if .Values.actions.cronPublishTpl.enabled }}
{{- if .Values.actions.cronPublishTpl.runAt }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "chart.fullname" . }}-publish-tpl
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  ttlSecondsAfterFinished: 30
  backoffLimit: 1
  template:
    spec:
      serviceAccountName: {{ include "chart.serviceAccountName" . }}
      restartPolicy: OnFailure
      containers:
      - name: node
        image: node:16
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        - |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip && ./aws/install
          npx directus schema snapshot --yes ./snapshot.yaml
          aws s3 cp ./snapshot.yaml s3://{{ .Values.actions.cronPublishTpl.s3Bucket }}/{{ .Values.actions.cronPublishTpl.name }}/{{ .Values.actions.cronPublishTpl.runAt }}.yaml

        {{- if .Values.appSecretName }}
        envFrom:
        - secretRef:
            name: {{ .Values.appSecretName }}
        {{- end }}

        env:
        {{- range $key, $value := .Values.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}

        {{- if .Values.extendEnv }}
        {{- range $key, $value := .Values.extendEnv }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{- end }}
{{- end }}
{{- end }}
