{{- if .Values.actions.cronSnapshot.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "chart.fullname" . }}-snapshot
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.actions.cronSnapshot.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ include "chart.serviceAccountName" . }}
          restartPolicy: OnFailure
          containers:
          - name: db-backup
            image: ghcr.io/benjamin-maynard/kubernetes-cloud-mysql-backup:v2.6.0
            imagePullPolicy: IfNotPresent
            env:
              - name: AWS_DEFAULT_REGION
                value: eu-north-1
              - name: AWS_BUCKET_NAME
                value: {{ .Values.actions.cronSnapshot.s3Bucket }}
              - name: AWS_BUCKET_BACKUP_PATH
                value: snapshot/{{ .Values.env.DB_DATABASE }}
              - name: TARGET_DATABASE_HOST
                value: {{ .Values.env.DB_HOST }}
              - name: TARGET_DATABASE_PORT
                value: "3306"
              - name: TARGET_DATABASE_NAMES
                value: {{ .Values.env.DB_DATABASE }}
              - name: TARGET_DATABASE_USER
                value: {{ .Values.env.DB_USER }}
              - name: TARGET_DATABASE_PASSWORD
                value: {{ .Values.env.DB_PASSWORD }}
              - name: BACKUP_TIMESTAMP
                value: "%Y%m%d_%H%m"

{{- end }}
---
{{- if .Values.actions.cronSnapshot.enabled }}
{{- if .Values.actions.cronSnapshot.runAt }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "chart.fullname" . }}-snapshot
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    runtAt: {{ .Values.actions.cronSnapshot.runAt }}
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 1
  template:
    spec:
      serviceAccountName: {{ include "chart.serviceAccountName" . }}
      restartPolicy: OnFailure
      containers:
      - name: db-backup
        image: ghcr.io/benjamin-maynard/kubernetes-cloud-mysql-backup:v2.6.0
        imagePullPolicy: IfNotPresent
        env:
          - name: AWS_DEFAULT_REGION
            value: eu-north-1
          - name: AWS_BUCKET_NAME
            value: {{ .Values.actions.cronSnapshot.s3Bucket }}
          - name: AWS_BUCKET_BACKUP_PATH
            value: snapshot/{{ .Values.env.DB_DATABASE }}
          - name: TARGET_DATABASE_HOST
            value: {{ .Values.env.DB_HOST }}
          - name: TARGET_DATABASE_PORT
            value: "3306"
          - name: TARGET_DATABASE_NAMES
            value: {{ .Values.env.DB_DATABASE }}
          - name: TARGET_DATABASE_USER
            value: {{ .Values.env.DB_USER }}
          - name: TARGET_DATABASE_PASSWORD
            value: {{ .Values.env.DB_PASSWORD }}
          - name: BACKUP_TIMESTAMP
            value: "manual-%Y%m%d_%H%m"
{{- end }}
{{- end }}
