{{- if (and .Values.ledger.enabled .Values.ledger.sa.create) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chart.serviceAccountName" . }}-ledger
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  {{- with .Values.ledger.sa.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with .Values.ledger.sa.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "chart.serviceAccountName" . }}-ledger-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "chart.serviceAccountName" . }}-ledger-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "chart.serviceAccountName" . }}-ledger-role
subjects:
- kind: ServiceAccount
  name: {{ include "chart.serviceAccountName" . }}-ledger
{{- end -}}
