{{- if .Values.ledger.enabled -}}
apiVersion: v1
kind: Service
metadata:
  {{- if .Values.webapp.svc.name }}
  name: {{ .Values.webapp.svc.name }}
  {{- else }}
  name: {{ include "chart.fullname" . }}-ledger
  {{- end }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    gigapress.catex.se/app_name: ledger-apiserver
  {{- with .Values.ledger.svc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.ledger.svc.type }}
  ports:
    - port: {{ .Values.ledger.svc.port }}
      targetPort: apiserver
      protocol: TCP
      name: http
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
    gigapress.catex.se/app_name: ledger-apiserver
{{- end -}}
