apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgA6XQgUg3GUuQ3CYVmV2USthXvPQWtq/BN+i8q0m2KuC9AjCpHdGyHAx0//FrjRtuJHQhdcQP00Mn5yNyOxy/nHzPpiR5rWeDdqJuuFJHpdymHcg8nz5nPg1pw5ONRTcPE3TR+FejmxGInH4HDeDVvmW7OrHNBJFIeE8wLaoKJAxnSK6zFV0ErDfBqpPMC4v2IVaBOJTCSX+vAGfYJ/fUNCSN2S+PQJ3uQnam4FgOdDftc8R08pP91uk5arA41qOepyCH5i1E6eROMa5Jcqeh/a6DBh14cEG29VUstWeop6hLXg9Ku67Kl4LfgCI8HDk/5YlikZ6jPD1t85rFZB4Zfo//uxyfIL4ePrXJtxA0/IF4Oa8tMZQQaRGuiIp+fka5i/FHB1FpmBWTrnf5Fon8MqgiWHcSbgn0578cckkYSSk2OqOrb3jc+tBVsXsLf3JbcxBFS9UKlFP9I8BFkNlE1o0AEIqgHrMFT+IWUin/xtgs9IPaCRGIuPq+BAAhiFCIDfesmM6/p3AhN2t4pcvNSULmQcZgS4Z0Sr970pBjr1LZ1nI5Z1aZR2ynFsi3IRhN6xrqgDhrDDbYrIHnKtwQoBE6ixwZEsoY/p1/RZ5PZbIYWan82lzOSoyhXA1W55xSNGAgPsGDch7NeezUR72kqrTg4P9K/jNjGXijlOOTcxTjAnn6RmAsrEi3hmWCNFrscOPl8gJMNHkk2XcaEKsIG+5TEyP7QkNk+aU/GzCdRtF2wTO+ditcrupxnszx8IqqwRQH3SeG2c/+8WVGZLsTjTIHETVPYPrsXwEhFL2AXPHN3L23Qy+QEtHS29izxHBYD3QaIiTgB/3MH1eokltYS8o+1fjQ==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system
    type: Opaque

