apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgA+7dcrILG3E2hU6b9g2Eeuiaghto4ZySESqmrdDeyl3qoxGPWT3EmTs9hh2LHzFFK/V0mWN3yTtSPx9b1dQDGJ3IWdRN9IAh/vnex6oHdVMVQH6NYscTphCa4anwWs8M2+4NqYZhLKCwwA460TD3ComMkgPF4y7kR0/F+ORZI5/3baOyTfeDZTW6HYgL5DMmuYP+DHEfKm46nO5hUFMJiZX2ZieBLKjkVR8rkV9gKa3M3Rpjq/K1kYlFChzzfRQIrU9/DSwv4t1W42OPL4o/vvG3dfMojqfnJXm76Y3pstOIu/0acYvpztvz0xAiF0zbajNelaKrlsrSXcih3Y/Wr7gE57uch+BtVXxtkM79sQnhq1DzeJ9L+S3kjRXT5Qrv9wJlOI4TF3gE6IkW4dpwfH3RyNyXTQsIxprOv/C18oTbjBNsnpQ7CgZ8/e8ljnDrxGahXmOLqSnQekHD3X7pzMfE3THWqTib90/97GUsy4ACot1aygrOZSCu8L6WxvHtHOt3D5aBGLXEgq9WRB8CB0vVIwUreimWDNPPrGtJfmX6k3Qd+O/8QulCcT1Eqn5iwhIEj6Ow2BZpjgSttX9cWleFnpFO7cPcFgQ2NKt1avybCAW3goy33KpRsswzmtr3L/3AbXs2JzjyNCPJfQ2bnrqJyVNkDXmSid+GRfeCqaPJr5rlmrbBL6AS8TTKgNhkTqwDpNOvu4L2LgCsyuYCsSt93AfCG+U4ndq7MPgY20VgEsAvk0ZDNfpG/Olq8C/QrBb7kENvvnG5pE4pvy296ZkuoU27AysT7/m8mnXGUqOk4FPK1jQAlK9EYaPTqUS3BQTAYJFOm9MPOtLgO5o1D36jF22g==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system
    type: Opaque

