apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgAZY+bUn2KTJKwVE/TqqdTPCUaL1WeEeCPh2ERg8yLkjc3laPTnqGtfsdJvmllIU+DHIYU3VcCpgMhHrXf4ZnnK8eaEeMyLV5mAbvQR1PzdtgtNYx+VJiUNReHm+w4nXxT7GhzQbKx/X83CCngUoGCGrrAkL1jRM9VyROYiON/L+zmloJbn4l21uueGyikkw9//SgHlRp8hYfjc+3d5vqsmaueJFNVpXRyWPxoFXwlZ2skOcumBWVbdqVe7h6lkxAEab7Prac4Ufqx/h2FVzT/236RCAVdlJZWLhktxNpZ8A6rNoRQ1dPVYPszoOLEDJ1IaHlqSRItQ18J7mZUZ7zChiBO/2QNSWBui23y53JDRKjuZDieSjm4fOvb+Q7Uq7vrQ4o1JqhS9+KReR2/z9K8TQk+vnVy9E8XWBx0Pzf+h574WHjxjyOGM7jwRcmbwQzDEZY+HiG4Fu8aVZhItdyieLN9UkEEPNNpEN2lQpMtGYuBmERX+9WynLagTn1bNTB8fTKtac7yO7XcF1IolVmKrqU6mi+nMF5ePZZfpKwuVaYoUkXN779If3F01gvLwk1yKVtevblsAVVegfOesuBWwZetDoqCwIdRiGitRFipd8HrG/5D9R08GYK6QIatFPxTxBQz97Az3iX4GDzvzGrRvhUDb3v7BZGMQWpNA9MuDu65M/DOrV4KGShuPy7vEmWr0wqPb4MyW6jbv2IHmTA2SYGpvfEyw2IhSeqDyrmceih2dwkSYJcXMktRfdCY5rmFhHNbJD+jfFGyF+5PuUtlGZy0fw4RtEbSDlOX85bvOJgPXuj5qoIlBPkOm8sa90XHjbAMOSbWyverraeYxqxC4qJ7uBA==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system
    type: Opaque

