apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: cloudfront.aws.gigapress.catex.se
  labels:
    crossplane.io/xrd: xworkspaces.gigapress.catex.se
    provider: aws
    type: workspace
    tier: standard
spec:
  writeConnectionSecretsToNamespace: crossplane-system

  compositeTypeRef:
    apiVersion: gigapress.catex.se/v1alpha1
    kind: XWorkspace

  patchSets:
    - name: common
      patches:
        - fromFieldPath: "spec.region"
          toFieldPath: "spec.forProvider.region"
        - fromFieldPath: "spec.deletionPolicy"
          toFieldPath: "spec.deletionPolicy"

  resources:
    - name: cloudfront
      base:
        apiVersion:
        kind:
        spec:
          forProvider:


