apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: gigapress-ws
  annotations:
    provider: aws
spec:
  crossplane:
    version: ">=v1.4.0-0"
  dependsOn:
    - provider: crossplane/provider-sql
      version: ">=v0.5.0"
    - provider: crossplane/provider-helm
      version: ">=v0.10.0"
