apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xworkspaces.gigapress.catex.se
spec:
  group: gigapress.catex.se
  names:
    kind: XWorkspace
    plural: xworkspaces
    categories:
      - gigapress
  claimNames:
    kind: Workspace
    plural: workspaces
  connectionSecretKeys:
    - username
    - password
    - endpoint
    - port
  defaultCompositionRef:
    name: workspace.aws.gigapress.catex.se
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            description: The list extensions installed in workspace
            properties:
              name:
                type: string
                description: The name of this workspace

              region:
                type: string
                description: The region of this workspace

              orgRefName:
                type: string
                description: The name of org (XRD) which is this ws belongs to

              dbRefName:
                type: string
                description: The name of db (XRD) which is this ws connect to

              domain:
                type: string
                description: the main domain route53 reference

              subdomain:
                type: string
                description: The name of subdomain of workspase (empty is remove)

              deletionProtection:
                type: boolean
                description: The flag use to protect from delete action

              webapp:
                type: object
                description: the configuration of webapp attached
                properties:
                  enabled:
                    type: boolean
                    description: the flag use determine webapp attached
                  image:
                    type: string
                    description: the webapp's docker image
                  version:
                    type: string
                    description: the version of frontoffice's docker image
                  size:
                    type: integer
                    description: the replica size of ledger apiserver
                  sa:
                    type: object
                    description: the service account configuration
                    properties:
                      create:
                        type: boolean
                        description: determine create this service account or not
                      annotation:
                        type: object
                        description: the service account's annotations
                        x-kubernetes-preserve-unknown-fields: true
                  env:
                    type: object
                    description: the free property:value
                    x-kubernetes-preserve-unknown-fields: true
                  extVersion:
                    type: string
                    description: the version of frontoffice extension

              ledger:
                type: object
                description: the configuration of ledger attached
                properties:
                  enabled:
                    type: boolean
                    description: the flag use determine ledger attached
                  image:
                    type: string
                    description: the ledger apiserver image's link
                  version:
                    type: string
                    description: the version of ledger apiserver image
                  size:
                    type: integer
                    description: the replica size of ledger apiserver
                  env:
                    type: object
                    description: the free property:value
                    x-kubernetes-preserve-unknown-fields: true
                  region:
                    type: string
                    description: the region of ledger reside at
                  sa:
                    type: object
                    description: the service account configuration
                    properties:
                      create:
                        type: boolean
                        description: determine create this service account or not
                      annotation:
                        type: object
                        description: the service account's annotations
                        x-kubernetes-preserve-unknown-fields: true
                  extVersion:
                    type: string
                    description: the version of ledger extension

              meilisearch:
                type: object
                description: the configuration of ledger attached
                properties:
                  enabled:
                    type: boolean
                    description: the flag use determine meilisearch attached
                  extVersion:
                    type: string
                    description: the version of meilisearch extension

              app:
                type: object
                description: The configuration of application
                properties:
                  adminEmail:
                    type: string
                    description: the admin email
                  adminPassword:
                    type: string
                    description: the admin password
                  env:
                    type: object
                    description: the free property:value
                    x-kubernetes-preserve-unknown-fields: true
                  image:
                    type: string
                    description: the core image's link
                  version:
                    type: string
                    description: the version of core application
                  chartVersion:
                    type: string
                    description: the version of helm chart
                  size:
                    type: integer
                    description: the replica size of application
                required:
                  - adminEmail
                  - adminPassword

              extensions:
                type: array
                items:
                  desciption: The configuration of extensions
                  type: object
                  properties:
                    name:
                      type: string
                      description: the name of extension which is extension registered
                    version:
                      type: string
                      description: the current version of this extension
                    minorAutoUpgrade:
                      type: boolean
                      description: the flag detect auto fetch minor version update
                    devMode:
                      type: boolean
                      description: the flag detect is dev environment
                  required:
                    - name
                    - version
              publishTpl:
                type: object
                description: configuration for publish template action
                properties:
                  name:
                    type: string
                    description: the name of template
                  schedule:
                    type: string
                    description: the cronjob schedule definition
                  enabled:
                    type: boolean
                    description: enable action
                  s3Bucket:
                    type: string
                    description: the destination s3 bucket
                  runAt:
                    type: string
                    description: the trigger time job run
              installFromTpl:
                type: object
                description: the optional to install new ws from template
                properties:
                  enabled:
                    type: boolean
                    description: active the option
                  name:
                    type: string
                    description: the name of template
                  version:
                    type: string
                    description: the version of template
                  s3Bucket:
                    type: string
                    description: the bucket name of template
              actions:
                type: object
                description: the actions of workspace
                properties:
                  chartVersion:
                    type: string
                    description: chart version of action release
                  snapshot:
                    type: object
                    description: attribute of take snapshot action
                    properties:
                      schedule:
                        type: string
                        description: the cronjob schedule definition
                      enabled:
                        type: boolean
                        description: enable action
                      s3Bucket:
                        type: string
                        description: the destination s3 bucket
                      runAt:
                        type: string
                        description: the trigger time job run

            required:
              - name
              - orgRefName
              - dbRefName
              - region
              - domain
              - subdomain
              - app
          status:
            description: A Status represents the observed state
            properties:
              acm:
                description: Freeform field - infor eks
                type: object
                x-kubernetes-preserve-unknown-fields: true
              ledger:
                description: Ledger status
                type: object
                x-kubernetes-preserve-unknown-fields: true
            type: object
