apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xworkspaces.gigapress.catex.se
spec:
  group: gigapress.catex.se
  names:
    kind: XWorkspace
    plural: xworkspaces
    categories:
      - gigapress
  claimNames:
    kind: Workspace
    plural: workspaces
  connectionSecretKeys:
    - username
    - password
    - endpoint
    - port
  defaultCompositionRef:
    name: workspace.aws.gigapress.catex.se
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            description: The list extensions installed in workspace
            properties:
              name:
                type: string
                description: The name of this workspace

              region:
                type: string
                description: The region of this workspace

              orgRefName:
                type: string
                description: The name of org (XRD) which is this ws belongs to

              dbRefName:
                type: string
                description: The name of db (XRD) which is this ws connect to

              domain:
                type: string
                description: the main domain route53 reference

              subdomain:
                type: string
                description: The name of subdomain of workspase (empty is remove)

              webapp:
                type: object
                description: the configuration of webapp attached
                properties:
                  enabled:
                    type: boolean
                    description: the flag for determine webapp attached
                  image:
                    type: string
                    description: the webapp's docker image
                  version:
                    type: string
                    description: the version of frontoffice's docker image
                  chartVersion:
                    type: string
                    description: the version of frontoffice's chart
                  env:
                    type: object
                    description: the free property:value
                    x-kubernetes-preserve-unknown-fields: true

              app:
                type: object
                description: The configuration of application
                properties:
                  adminEmail:
                    type: string
                    description: the admin email
                  adminPassword:
                    type: string
                    description: the admin password
                  env:
                    type: object
                    description: the free property:value
                    x-kubernetes-preserve-unknown-fields: true
                  image:
                    type: string
                    description: the core image
                  version:
                    type: string
                    description: the version of core application
                  chartVersion:
                    type: string
                    description: the version of helm chart
                  size:
                    type: integer
                    description: the replica size of application
                required:
                  - adminEmail
                  - adminPassword
              extensions:
                type: array
                items:
                  desciption: The configuration of extensions
                  type: object
                  properties:
                    name:
                      type: string
                      description: the name of extension which is extension registered
                    version:
                      type: string
                      description: the current version of this extension
                    minorAutoUpgrade:
                      type: boolean
                      description: the flag detect auto fetch minor version update
                    devMode:
                      type: boolean
                      description: the flag detect is dev environment
                  required:
                    - name
                    - version
            required:
              - name
              - orgRefName
              - dbRefName
              - region
              - domain
              - subdomain
              - app
          status:
            description: A Status represents the observed state
            properties:
              acm:
                description: Freeform field - infor eks
                type: object
                x-kubernetes-preserve-unknown-fields: true
            type: object
